car_rental/urls.py
from django.urls import include, path
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'car_rental'

urlpatterns = [
    path('', views.index, name='index'),
    path('car/', views.car, name='car'),
    path('addCar/', views.addCar, name='addCar'),
    path('transaction/', views.transaction, name='transaction'),
    path('article/', views.article, name='article'),
    path('articleView/', views.articleView, name='articleView'),
    path('carSearch/', views.carSearch, name='carSearch'),
    path(r'^viewCar/(?P<pk>\d+)/$', views.viewCar, name='viewCar'),
    path('rentCar/', views.rentCar, name='rentCar'),
]

pro_ppw_ga/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('car_rental.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

car_rental/models.py
from django.db import models
from django.forms import ModelForm

# Create your models here.

class Car(models.Model):
    car_name = models.CharField(max_length=30)
    user_name = models.CharField(max_length=30)
    year = models.CharField(max_length=4)
    city = models.CharField(max_length=30)
    price = models.CharField(max_length=30)
    description = models.TextField()

    def __str__(self):
        return self.car_name

class Transaction(models.Model):
    user_name = models.CharField(max_length=30)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.user_name

class Article(models.Model):
    title = models.CharField(max_length=30)
    date = models.DateField()
    short_desc = models.TextField(default="article")
    content = models.TextField()
    photo = models.ImageField(upload_to='images/', default= 'images/test.jpg')

    def __str__(self):
        return self.title


class Review(models.Model):
    user_name = models.CharField(max_length=30)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    message = models.TextField()
    date = models.DateField()
    RATING_CHOICES = [
        ('1', '1/5'),
        ('2', '2/5'),
        ('3', '3/5'),
        ('4', '4/5'),
        ('5', '5/5'),
    ]
    rating = models.CharField(max_length=1, choices=RATING_CHOICES)

    def __str__(self):
        return self.user_name

car_rental/forms.py
from django import forms
from django.forms import TextInput
from .models import Car, Transaction, Article, Review

class AddCarForm(forms.ModelForm): #TO DO
    
    class Meta:
        model = Car
        fields = [
            'car_name', 
            'user_name',
            'year',
            'city',
            'price',
            'description'
        ]
        labels = {
            'car_name': 'Car Name',
            'user_name': 'User Name',
            'year': 'Year',
            'city': 'City',
            'price': 'Price per Day',
            'description': 'Description'
        }
        widgets = {
            'car_name': forms.TextInput(attrs={'placeholder': 'Name of the car'}),
            'user_name': forms.TextInput(attrs={'placeholder': 'Your user name'}),
            'year': forms.TextInput(attrs={'placeholder': 'Manufacture year'}),
            'city': forms.TextInput(attrs={'placeholder': 'Location of the car'}),
            'price': forms.TextInput(attrs={'placeholder': 'Rate of rent per day'}),
            'description': forms.TextInput(attrs={'placeholder': 'Short description of your car'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

class DateInput(forms.DateInput):
    input_type = 'date'

class RentCarForm(forms.ModelForm): #TO DO

    class Meta:
        model = Transaction
        fields = [
            'user_name',
            'car',
            'start_date',
            'end_date',
        ]
        labels = {
            'user_name': 'User Name',
            'car': 'Car',
            'start_date': 'Start Rent Date',
            'end_date': 'End Rent Date'
        }
        widgets = {
            'user_name': forms.TextInput(attrs={'placeholder': 'Your user name'}),
            'car': forms.Select(attrs={'class':'form-control'}),
            'start_date': DateInput(),
            'end_date': DateInput(),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

car_rental/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import redirect

from .models import Car, Article, Transaction, Review
from . import forms
from .forms import AddCarForm, RentCarForm
import re

# Create your views here.
def index(request):
    car = Car.objects.all()
    response = {'car' : car}
    return render(request, 'index.html', response)

def car(request):
    car = Car.objects.all()
    response = {'car' : car}
    return render(request, 'car.html', response)

def carSearch(request):
    carTarget = request.POST['search']
    cars = Car.objects.all()
    pattern = re.compile(carTarget, re.IGNORECASE)
    car = filter(lambda car: re.search(pattern, car.car_name), cars)
    response = {'car' : car}
    return render(request, 'carSearch.html', response)

def viewCar(request, pk):
    car = Car.objects.get(id=pk)
    reviews = Review.objects.all()
    response = {
        'car' : car,
        'reviews': reviews
    }
    return render(request, 'viewCar.html', response)


def addCar(request):
    if request.method == 'POST':
        form = forms.AddCarForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('car_rental:car')
    else:
        form = forms.AddCarForm()
        return render(request, 'addCar.html', {'form': form})

def rentCar(request):
    transaction = Transaction.objects.order_by('-date')
    car = Car.objects.all()

    if request.method == 'POST':
        form = forms.RentCarForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('../transaction')

    else:
        form = forms.RentCarForm()
    return render(request, 'rentCar.html', {'transaction': transaction, 'form': form})

def transaction(request):
    car = Car.objects.all()
    transaction = Transaction.objects.all().order_by('-date')
    response = {'car' : car, 'transaction': transaction}
    return render(request, 'transaction.html', response)

def article(request):
    artic = Article.objects.all()
    response = {'article': artic}
    return render(request, 'article.html', response)

def articleView(request):
    arti_title = request.POST['title']
    articles = Article.objects.all()
    for article in articles:
        if arti_title == article.title:
            articleTarget = article
    response = {'article' : articleTarget}
    return render(request, 'articleView.html', response)

car_rental/templates/addCar.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



<body style="background-color: #E8E8E8;">
    <div class="container-fluid">
        <center><h1 class="title">REGISTER YOUR CAR!</h1></center>
    </div>

    <br>

    <div class="container" style="width: 60%; margin-bottom: 30px;">
        <form method="post" action="{% url 'car_rental:addCar' %}">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-sm-8" style="padding-left: 15px; padding-right: 15px; margin-left: auto; margin-right: auto; text-align: center;">
                    {% for fields in form %}
                        {{ fields.label_tag }}
                        <br>
                        {{ fields }}
                        <br>
                    {% endfor %}
                </div>
            </div>
            <div class="form-row">
                <input type="submit" class="button btnClass2" value="Add">
            </div>
        </form>
    </div>
</body>



{% endblock %}

car_rental/templates/article.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<title>Articles | RentACar</title>

<!------------------------------------------------------------friend list--------------------------------------------------------->

<div style="background-color: #E8E8E8;">
    <div class="container">
        <center><h1 class="title"style="padding: 4px;">ARTICLES</h1></center>
    </div>
    <br><br>

    <div class="container">
        <div class="row row-cols-1 row-cols-md-2">
            {% for article in article %}
            <form method="POST" action="{% url 'car_rental:articleView' %}">
                {% csrf_token %}
                <div class="col mb-4">
                    <div class="card" style="width: 100%">
                        <div class="card-header" style="background-color: white;border-radius: 25px 25px 0 0;">
                            <div class="row no-gutters align-items-end">
                                <div class="col">
                                    <h4 class="card-title style"">
                                            {{ article.title }}</a>
                                    </h4>
                                </div>
                                <div class="col">
                                    <h6 class="card-subtitle" style="text-align: end;">{{ article.date }}</h6>
                                </div>
                            </div>
                        </div>
                        <div class="card-body" align="center">
                            <div class="row no-gutters">
                                <div class="col-md-4">
                                    <img src="{{ article.photo.url }}" class="card-img-responsive" alt="IMAGE" style="width: 100%; float: left; margin-right: 10px; border-radius: 20px;">
                                </div>
                                <div class="col-md-1"></div>
                                <div class="col-md-7">
                                    <p class="card-text" align="start">{{ article.short_desc }}</p>
                                </div>
                            </div>
                            <input type="hidden" name='title' value='{{ article.title }}'>
                            <input class="button btnClass"type="submit" value='View article'>
                        </div>
                    </div>
                    <br>
                </div>
            </form>
            {% endfor %}
        </div>
    </div>



</div>

{% endblock %}

car_rental/templates/articleView.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<title>View Articles | RentACar</title>

<!------------------------------------------------------------friend list--------------------------------------------------------->

<div style="background-color: #E8E8E8; width: 100%; height: 120%;">
    <div class="container">
        <center><h1 class="title"style="padding: 4px;">ARTICLES</h1></center>
    </div>
    <br><br>
    <div class="container align-content-center">
        <div class="card" style="width: 100%;">
            <div class="card-header" style="background-color: white; border-radius: 25px 25px 0 0;">
                <div class="row no-gutters align-items-end">
                    <div class="col">
                        <h2 class="card-title" id="articletitle">
                            {{ article.title }}</a>
                        </h2>
                    </div>
                    <div class="col">
                        <h6 class="card-subtitle" style="text-align: end;">{{ article.date }}</h6>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        <img src="{{ article.photo.url }}" class="card-img-responsive" alt="IMAGE" style="width: 100%; float: left; margin-right: 10px;">
                    </div>
                    <div class="col-md-1"></div>
                    <div class="col-md-7">
                        <p class="card-text">{{ article.content }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

car_rental/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <!----------------------------------------------------------links------------------------------------------------------->

    <link href="https://fonts.googleapis.com/css?family=Muli:200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <script src="https://kit.fontawesome.com/d17701d3a2.js" crossorigin="anonymous"></script>
    
     <!--------------------------------------------------------------------------------------------------------------------->

    <title>RentACar</title>
</head>
<body>
    <!----------------------------------------------------------navigation bar------------------------------------------------------->

    <nav class="navbar navbar-expand-lg navbar-dark bg-none" id="mainNav">
        <a class="navbar-brand" href="#page-top"></a>
        <a class="navbar-brand" href="{% url 'car_rental:index' %}#welcome"><img src="{% static 'images/logo.png' %}" style="max-width: 200px;"></a>
        <button class="navbar-toggler navbar-toggler-right" style="background: #1A3852;" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>           
        <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link navbarfont" href="{% url 'car_rental:index' %}" style="padding: 10px;">HOME</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle navbarfont" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="padding: 10px;">
                    CARS
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item navbarfont" href="{% url 'car_rental:car' %}" style="margin: 0;">CARS AVAILABLE</a>
                    <a class="dropdown-item navbarfont" href="{% url 'car_rental:addCar' %}" style="margin: 0;">RENT YOUR CAR!</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link navbarfont" href="{% url 'car_rental:transaction' %}" style="padding: 10px;">TRANSACTION</a>
            </li>
            <li class="nav-item">
                <a class="nav-link navbarfont" href="{% url 'car_rental:article' %}" style="padding: 10px;">ARTICLES</a>
            </li>
        </ul>
        </div>
    </nav>


    {% block content %}
    {% endblock %}

    <!----------------------------------------------------------bootstrap script------------------------------------------------------->

    <script type="text/javascript" src="/static/js/jquery.js"></script>
    <script type="text/javascript" src="/static/js/popper.js"></script>
    <script type="text/javascript" src="/static/js/bootstrap.min.js"></script>
</body>
</html>

car_rental/templates/car.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<title>Cars | RentACar</title>

<body style="background: #E8E8E8;">
    <div class="container">
        <div class="row">
            <div class="col-sm-8"></div>
            <div class="col-sm">
                <form class="example" method="POST" action="{% url 'car_rental:carSearch' %}">
                    {% csrf_token %}
                    <input class="form.example" type="search" placeholder="Search a Car..." name="search">
                    <button type="submit"><i class="fa fa-search" style="border-radius: 20px;max-width: 10px;"></i></button>
                </form>
            </div>
        </div>
    </div>
        
    <br>
    <div class="container-fluid" style="margin: 0;"><h1 class="title">CARS</h1></div>

    <center><div class="container" style="margin: 0;">
        <div class="d-flex flex-wrap justify-content-center">
        {% for car in car %}
        <form action="{% url 'car_rental:viewCar' car.id%}" method="POST">
        {% csrf_token %}
        <div class="card">
            <div class="card-body text-center">
                <img src="{% static 'images/car.png' %}" class="pict">
                <h5 class="card-title">{{ car.car_name }}</h5>
                <h6 class="card-subtitle mb-2 text-muted" style="margin-bottom: 4px;">{{ car.city }}</h6>
                <p class="card-text" style="margin-bottom: 8px;">Rp. {{ car.price }},00 / day</p>
                <input type='hidden' name='car_name' value='{{ car.car_name }}'>
                <input type='hidden' name='city' value='{{ car.city }}'>
                <input type='hidden' name='price' value='{{ car.price }}'>
                <input type="submit" class="button btnClass" value='View Details'>
            </div>
          </div>
        </form>
        {% endfor %}
        </div>
    </div></center>

</body>

{% endblock %}

car_rental/templates/carSearch.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<body style="background: #E8E8E8;">
    <div class="container">
        <div class="row">
            <div class="col-sm-8"></div>
            <div class="col-sm">
                <form class="example" method="POST" action="{% url 'car_rental:carSearch' %}">
                    {% csrf_token %}
                    <input class="form.example" type="search" placeholder="Search a Car..." name="search">
                    <button type="submit"><i class="fa fa-search" style="border-radius: 20px;max-width: 10px;"></i></button>
                </form>
            </div>
        </div>
    </div>
    <br>
    <div class="container-fluid"><h1 class="title">CARS</h1></div>

    <div class="container" style="margin: 0;">
        <div class="d-flex flex-wrap justify-content-center">
        {% for car in car %}
        
        <form action="{% url 'car_rental:viewCar' car.id%}" method="POST">
        {% csrf_token %}
        <div class="card">
            <div class="card-body text-center">
                <img src="{% static 'images/car1.jpg' %}" class="pict">
                <h5 class="card-title">{{ car.car_name }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ car.city }}</h6>
                <p class="card-text">{{ car.price }} / day</p>
                <input type='hidden' name='car_name' value='{{ car.car_name }}'>
                <input type='hidden' name='city' value='{{ car.city }}'>
                <input type='hidden' name='price' value='{{ car.price }}'>
                <input type="submit" class="button btnClass" value='View Details.'>
            </div>
          </div>
        </form>

        {% endfor %}
        </div>
    </div>
</body>

{% endblock %}

car_rental/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<title>RentACar!</title>

<body id="home">
    <div class="container">
        <div class="row">
            <div class="col-sm">

            </div>
            <div class="col-sm">
                <br><br><br>
                <center><h2 id="welcome">Welcome to RentACar!</h2></center>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-sm">
            </div>
            <div class="col-sm">
                <form class="form-inline my-2 my-lg-0 example" method="POST" action="{% url 'car_rental:carSearch' %}">
                    {% csrf_token %}
                    <input type="form-control mr-sm-2" placeholder="Search a Car..." name="search">
                    <button type="submit"><i class="fa fa-search" style="border-radius: 20px;max-width: 10px;"></i></button>
                </form>
            </div>
        </div>
    </div>

</body>

{% endblock %}

car_rental/templates/rentCar.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<body style="background-color: #E8E8E8;">

    <div class="container-fluid title"><h1>RENT FORM</h1></div> <br><br>

    <div class="container">
        <center>
            <h2>{{ car.car_name }}</h2>
            <h3>{{ car.user_name }}</h3>
            <h4>{{ car.city }} {{ car.year }}</h4>
        </center>
    </div>

    <br><br>

    <div class="container">
        <form method="post" action="{% url 'car_rental:rentCar' %}">
            {% csrf_token %}

            <div class="form-row">
                <div class="form-group col-sm-8" style="padding-left: 15px; padding-right: 15px; margin-left: auto; margin-right: auto; text-align: center;">
                    {% for fields in form %}
                        {{ fields.label_tag }}
                        <br>
                        {{ fields }}
                        <br>
                    {% endfor %}
                </div>
            </div>
            <div class="form-row">
                <input type="submit" class="button btnClass" value="SUBMIT">
            </div>
        </form>
    </div>
</body>

{% endblock %}

car_rental/templates/transaction.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<title>Transaction</title>

<body style="background: #E8E8E8;">
    <div class="container-fluid">
        <center><h1 class="title">TRANSACTIONS</h1></center>
    </div>

    <div class="container">
        <br>

        <table class="table">
            <thead class="thead-light">
            <tr>
                <th scope="col" style="color: #243370">User Name</th>
                <th scope="col" style="color: #243370">Car</th>
                <th scope="col" style="color: #243370">Rent Start Date</th>
                <th scope="col" style="color: #243370">Rent End Date</th>
                <th scope="col" style="color: #243370">Date</th>
            </tr>
            </thead>
            <tbody>
                {% for transaction in transaction %}
                <tr>
                    <td style="text-align: center;">{{ transaction.user_name }}</td>
                    <td style="text-align: center;">{{ transaction.car }}</td>
                    <td style="text-align: center;">{{ transaction.start_date }}</td>
                    <td style="text-align: center;">{{ transaction.end_date }}</td>
                    <td style="text-align: center;">{{ transaction.date }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>

{% endblock %}

car_rental/templates/viewCar.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<body style="background: #E8E8E8;">
    <center><div class="container_fluid"><div class="header-line"></div></div></center>

    <div class="container" style="margin-bottom:30px;">
        <center>
            <br>
            <img src="{% static 'images/car.png' %}" class="pict" style="max-width: 200px;">
            <h2 class="review" id="carname">{{ car.car_name }}</h2>
            <p class="review">{{ car.user_name }} </p>
            <h4 class="review">{{ car.city }}  {{ car.year }}</h4>
            <h4 class="review">Rp. {{ car.price }},00 / day</h4>
            <p class="review">{{ car.description }}</p><br><br>
            <form method="POST" action="{% url 'car_rental:rentCar' %}">
                {% csrf_token %}
                <input type='hidden' name='car_name' value='{{ car.car_name }}'>
                <input type='hidden' name='user_name' value='{{ car.user_name }}'>
                <input type='hidden' name='city' value='{{ car.city }}'>
                <input type='hidden' name='year' value='{{ car.year }}'>
                <input class="button btnClass2" type="submit" value="Rent now!">
            </form>
        </center>
    </div>


    <div class="container-fluid">
        <center>
        <h1 class="title">REVIEWS</h1>
        <br>
        <table class="table table-striped" style="text-align: center;">
            <thead>
                <tr>
                    <th scope="col-3">User Name</th>
                    <th scope="col-6">Message</th>
                    <th scope="col-2">Review Date</th>
                    <th scope="col-1">Rating (out of 5)</th>
                </tr>
            </thead>
            <tbody>
                {% for review in reviews %}
                {% if review.car == car %}
                <tr>
                    <td style="text-align: center;">{{ review.user_name }}</td>
                    <td style="text-align: center;">{{ review.message }}</td>
                    <td style="text-align: center;">{{ review.date }}</td>
                    <td style="text-align: center;">{{ review.rating }}</td>
                </tr>
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
        </center>
    </div>

</body>

{% endblock %}